enum Channels {
    SEVEN11 = "711_direct",
    BAYD = "BAYD",
    CEBL = "CEBL",
    LBC = "LBC",
    MLH = "MLH",
    SMR = "SMR",
    RDS = "RDS",
    ECPY = "ECPY",
    PLWN = "PLWN",
    RDP = "RDP",
    RLNT = "RLNT",
    POSSIBLE = "posible",
    PARNERPAY = "partnerpay",
    PAYNGO = "payngo",
    DA5 = "da5",
    ECPAY = "ecpay",
    USSC = "ussc",
    Rustan = "rustan",
    SHOPWISE = "shopwise",
    TAMBUNTING = "tmbntng",
    CVM = "cvm",
    WELLCOME = "wellcome",
    EXPY = "EXPY",
    BPI = "BPIA",
    UNIONBANK = "UBPB",
    GCASH = "gcash",
    RCBC = "RCBC",
    GRABPAY = "grabpay",
    CARD = "visamc",
    BNPL = "billease",
}
export { Channels };


